export { nav } from './nav'
export { HomeView } from './views/home-view'
export { ProductsView } from './views/products-view'
export { NavDemoView } from './views/nav-demo-view'
export { mapNavDemoItems } from './map-nav-demo'
export { PageRenderer } from '@erp/front-experience/react'
export type { FrontPageBlock } from '@erp/front-experience'
export type { FrontNavDemoItem } from './types'
export type { FrontNavSourceItem } from './map-nav-demo'
